# ============================================================
# PROJECT : SquidTchat
# AUTHOR  : W.Sanquer
# DATE    : 2026
# ============================================================

name: SquidTchat

services:

  # --------------------------------------------------------
  # Backend : serveur WebSocket Qt6 C++
  # --------------------------------------------------------
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: squidtchat-backend
    ports:
      - "1234:1234"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/1234'"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 5s

  # --------------------------------------------------------
  # Frontend : fichiers statiques servis par Nginx
  # --------------------------------------------------------
  frontend:
    image: nginx:alpine
    container_name: squidtchat-frontend
    ports:
      - "8080:80"
    volumes:
      - ../SquidFrontend:/usr/share/nginx/html
    environment:
      WS_HOST: "10.16.25.9" #Choisir l'IP de deploiement du projet
    entrypoint: /bin/sh -c "echo \"window.SQUIDTCHAT_WS_URL = 'ws://$$WS_HOST:1234';\" > /usr/share/nginx/html/config/config.js && nginx -g 'daemon off;'"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped